# Build java-web-json.war without Maven
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

$buildDir = Join-Path $root "build"
$classesDir = Join-Path $buildDir "WEB-INF\classes"
$libDir = Join-Path $buildDir "WEB-INF\lib"
$warFile = Join-Path $buildDir "java-web-json.war"
$frontend = Join-Path $root "frontend"
$srcDir = Join-Path $root "src\main\java"
$webInfSrc = Join-Path $root "src\main\webapp\WEB-INF"

Write-Host "Building WAR..." -ForegroundColor Cyan

if (Test-Path $buildDir) {
    Remove-Item -Recurse -Force $buildDir
}
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null
New-Item -ItemType Directory -Force -Path $classesDir | Out-Null
New-Item -ItemType Directory -Force -Path $libDir | Out-Null

Copy-Item -Path (Join-Path $frontend "*") -Destination $buildDir -Recurse -Force

$webInf = Join-Path $buildDir "WEB-INF"
$webXmlSrc = Join-Path $webInfSrc "web.xml"
$webXmlDest = Join-Path $webInf "web.xml"
if (Test-Path $webXmlSrc) {
    Copy-Item -Path $webXmlSrc -Destination $webXmlDest -Force
} else {
    @(
        "<?xml version=""1.0"" encoding=""UTF-8""?>"
        "<web-app xmlns=""https://jakarta.ee/xml/ns/jakartaee"""
        "         xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"""
        "         xsi:schemaLocation=""https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd"""
        "         version=""6.0"">"
        "    <display-name>TA Recruitment System</display-name>"
        "    <welcome-file-list>"
        "        <welcome-file>index.html</welcome-file>"
        "    </welcome-file-list>"
        "</web-app>"
    ) | Set-Content -Path $webXmlDest -Encoding UTF8
}

$dataDirFull = [System.IO.Path]::GetFullPath((Join-Path $root "data"))
$uploadCvFull = [System.IO.Path]::GetFullPath((Join-Path $root "uploads\cv"))
$dataDirProp = $dataDirFull.Replace("\", "/")
$uploadCvProp = $uploadCvFull.Replace("\", "/")
$propsDest = Join-Path $webInf "app-settings.properties"
$propsText = @"
# Auto-generated by build-no-maven.ps1
dataDir=$dataDirProp
uploadsCvDir=$uploadCvProp
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($propsDest, $propsText.TrimEnd() + [Environment]::NewLine, $utf8NoBom)

if (Test-Path $srcDir) {
    $javaFiles = @(Get-ChildItem -Path $srcDir -Recurse -Filter "*.java")
    if ($javaFiles.Count -gt 0) {
        $deps = @(
            @{ Name = "jakarta.servlet-api-6.0.0.jar"; Url = "https://repo.maven.apache.org/maven2/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar" }
            @{ Name = "jbcrypt-0.4.jar"; Url = "https://repo.maven.apache.org/maven2/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar" }
            @{ Name = "gson-2.10.1.jar"; Url = "https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar" }
        )
        foreach ($dep in $deps) {
            $jarPath = Join-Path $libDir $dep.Name
            if (-not (Test-Path $jarPath)) {
                Write-Host "Downloading $($dep.Name)..." -ForegroundColor Yellow
                try {
                    Invoke-WebRequest -Uri $dep.Url -OutFile $jarPath -TimeoutSec 60
                } catch {
                    Write-Warning "Failed to download $($dep.Name): $_"
                }
            }
        }
        $allJars = @(Get-ChildItem -Path $libDir -Filter "*.jar" | ForEach-Object { $_.FullName })
        $classpath = ($allJars -join ";")
        $targetClasses = Join-Path $root "target\classes"
        if (Test-Path $targetClasses) {
            $classpath = $classpath + ";" + $targetClasses
        }
        if ($classpath) {
            $sources = ($javaFiles | ForEach-Object { $_.FullName }) -join " "
            $javacArgs = @("-encoding", "UTF-8", "-cp", $classpath, "-d", $classesDir) + ($javaFiles | ForEach-Object { $_.FullName })
            Write-Host "Compiling Java sources..." -ForegroundColor Yellow
            & javac @javacArgs
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "javac reported errors; WAR will still include static frontend."
            }
        }
    }
}

Write-Host "Packaging WAR..." -ForegroundColor Cyan
if (Test-Path $warFile) { Remove-Item $warFile -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = [System.IO.Compression.ZipFile]::Open($warFile, "Create")
foreach ($file in Get-ChildItem -Recurse -Path $buildDir -File | Where-Object { $_.Extension -ne ".war" }) {
    $relativePath = $file.FullName.Substring($buildDir.Length + 1).Replace("\", "/")
    $entry = $zip.CreateEntry($relativePath)
    $entryStream = $entry.Open()
    $fileStream = [System.IO.File]::OpenRead($file.FullName)
    $fileStream.CopyTo($entryStream)
    $fileStream.Close()
    $entryStream.Close()
}
$zip.Dispose()

$warSize = [math]::Round((Get-Item $warFile).Length / 1KB, 2)
Write-Host "Built: $warFile ($warSize KB)" -ForegroundColor Green
