# Build WAR without Maven: Jakarta EE 9 / Tomcat 10+ (jakarta.*).
# Requires: JDK 17+ on PATH; network on first run for JAR download.
# 打包时会自动生成 WEB-INF/app-settings.properties，把 data/uploads 指到「本脚本所在工程目录」，无需改 Tomcat。
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$build = Join-Path $root "build"
$warDir = Join-Path $build "java-web-json"
$lib = Join-Path $root "build\compile-lib"
New-Item -ItemType Directory -Force -Path $lib | Out-Null

# Compile-only (Tomcat provides these at runtime — do not put in WEB-INF/lib)
# Runtime: gson, jbcrypt, JSTL API + GlassFish JSTL impl
$jars = @(
  @{ u = "https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar"; n = "jakarta.servlet-api-5.0.0.jar"; compileOnly = $true },
  @{ u = "https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.0.0/jakarta.servlet.jsp-api-3.0.0.jar"; n = "jakarta.servlet.jsp-api-3.0.0.jar"; compileOnly = $true },
  @{ u = "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.11.0/gson-2.11.0.jar"; n = "gson-2.11.0.jar"; compileOnly = $false },
  @{ u = "https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0/jakarta.servlet.jsp.jstl-api-2.0.0.jar"; n = "jakarta.servlet.jsp.jstl-api-2.0.0.jar"; compileOnly = $false },
  @{ u = "https://repo1.maven.org/maven2/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar"; n = "jakarta.servlet.jsp.jstl-2.0.0.jar"; compileOnly = $false },
  @{ u = "https://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar"; n = "jbcrypt-0.4.jar"; compileOnly = $false }
)
foreach ($j in $jars) {
  $p = Join-Path $lib $j.n
  if (-not (Test-Path $p)) { Invoke-WebRequest -Uri $j.u -OutFile $p -UseBasicParsing }
}

if (Test-Path $warDir) { Remove-Item $warDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path (Join-Path $warDir "WEB-INF\classes"), (Join-Path $warDir "WEB-INF\lib") | Out-Null
Copy-Item -Path (Join-Path $root "src\main\webapp\*") -Destination $warDir -Recurse -Force
Copy-Item -Path (Join-Path $root "frontend\*") -Destination $warDir -Recurse -Force

# 数据写到本工程目录下的 data/ 与 uploads/cv/（绝对路径写入 war，免改 Tomcat；换电脑需重新执行本脚本打包）
$dataDirFull = [System.IO.Path]::GetFullPath((Join-Path $root "data"))
$uploadCvFull = [System.IO.Path]::GetFullPath((Join-Path $root "uploads\cv"))
function ConvertTo-JavaPath([string]$winPath) { return ($winPath -replace '\\', '/') }
$propsDest = Join-Path $warDir "WEB-INF\app-settings.properties"
$propsLines = @(
  '# Auto-generated by build-no-maven.ps1. Re-run script if you move the project folder.',
  '# Data lives under this repo; others should rebuild the war on their PC for correct paths.',
  "dataDir=$(ConvertTo-JavaPath $dataDirFull)",
  "uploadsCvDir=$(ConvertTo-JavaPath $uploadCvFull)"
)
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($propsDest, $propsLines, $utf8NoBom)

$runtimeJars = $jars | Where-Object { -not $_.compileOnly } | ForEach-Object { Join-Path $lib $_.n }
Copy-Item -Path $runtimeJars -Destination (Join-Path $warDir "WEB-INF\lib") -Force

$cp = ($jars | ForEach-Object { Join-Path $lib $_.n }) -join ";"
$src = Get-ChildItem -Path (Join-Path $root "src\main\java") -Filter "*.java" -Recurse | ForEach-Object { $_.FullName }
& javac --release 17 -encoding UTF-8 -d (Join-Path $warDir "WEB-INF\classes") -cp $cp @src
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Push-Location $build
& jar cf java-web-json.war -C java-web-json .
Pop-Location
Write-Host "Done (Tomcat 10+). Deploy: $warDir or $build\java-web-json.war"
